# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38fbd567b8f37e0cdf196a60292bafc010f9c2751c439c15190e92c6c2fc763b88d5518e5adf357232110c167755ac15661124604fc0dc8a23ddbe1e182ff40b

test:
  secret_key_base: 0cd9c70a2da00bd2508edfbb3a1545c52328683c6dc773bf4cc2c87eed5f3df7762b2bc41792998d344b80d1356d3fabc698a42871875c33e2cd6a016c01e124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
